"use client";

// Generated by scripts/build-examples.mjs. Do not edit by hand.
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

export const examples: Record<string, ComponentType | undefined> = {
  "frame-source-demo": dynamic(() => import("@/components/examples/frame-source-demo")),
};
